"use client";
import { useEffect, useState } from "react";

type Holding={symbol:string;name:string;market:string;country:string;currency:string;quantity:number;latestPrice:number;marketValue:number;unrealizedPnl:number;unrealizedPnlPercent:number;weight:number};
type Allocation={label:string;value:number;percentage:number};
type Snapshot={broker:string;mode:string;updatedAt:string;totalValue:number;currency:string;holdings:Holding[];countryAllocation:Allocation[];marketAllocation:Allocation[]};
const api=process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8080";
const money=(value:number,currency:string)=>new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:0}).format(value);
const percent=(value:number)=>`${value >= 0 ? "+" : ""}${value.toFixed(1)}%`;

export default function Home(){ const [data,setData]=useState<Snapshot>(); const [error,setError]=useState<string>(); const [loading,setLoading]=useState(true); const load=async()=>{setLoading(true);setError(undefined);try{const res=await fetch(`${api}/api/v1/portfolio`);if(!res.ok) throw new Error("Portfolio unavailable");setData(await res.json())}catch{setError("Couldn’t reach the portfolio service. Start the API, then refresh.")}finally{setLoading(false)}}; useEffect(()=>{void load()},[]); if(loading)return <main className="shell"><p className="eyebrow">OPEN PORTFOLIO TRACKER</p><h1>Loading your portfolio…</h1></main>; if(error)return <main className="shell"><p className="eyebrow">OPEN PORTFOLIO TRACKER</p><h1>Your dashboard is waiting.</h1><p>{error}</p><button onClick={()=>void load()}>Try again</button></main>; if(!data)return null; return <main className="shell"><header><div><p className="eyebrow">OPEN PORTFOLIO TRACKER</p><h1>Invest with perspective.</h1><p className="subtle">A clear view of your {data.broker} holdings and allocation.</p></div><button onClick={()=>void load()}>Refresh</button></header>{data.mode==="demo"&&<aside><strong>Demo portfolio</strong><span>Add your Tiger credentials to <code>backend/.env</code> to see live holdings.</span></aside>}<section className="hero"><p>Total portfolio value</p><h2>{money(data.totalValue,data.currency)}</h2><span>Updated {new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(data.updatedAt))}</span></section><section className="grid"><Allocation title="By country" items={data.countryAllocation}/><Allocation title="By market" items={data.marketAllocation}/></section><section className="holdings"><div className="section-title"><div><p className="eyebrow">YOUR HOLDINGS</p><h2>What you own</h2></div><span>{data.holdings.length} positions</span></div><div className="table"><div className="row heading"><span>Holding</span><span>Weight</span><span>Value</span><span>Return</span></div>{data.holdings.map(h=><div className="row" key={h.symbol}><span><b>{h.symbol}</b><small>{h.name} · {h.country}</small></span><span>{h.weight.toFixed(1)}%</span><span>{money(h.marketValue,h.currency)}</span><span className={h.unrealizedPnl>=0?"positive":"negative"}>{percent(h.unrealizedPnlPercent)}</span></div>)}</div></section></main> }
function Allocation({title,items}:{title:string;items:Allocation[]}){return <section className="allocation"><h2>{title}</h2>{items.map(item=><div className="allocation-row" key={item.label}><div><span>{item.label}</span><b>{item.percentage.toFixed(1)}%</b></div><div className="bar"><i style={{width:`${item.percentage}%`}}/></div></div>)}</section>}
